import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'injection.config.dart';

final GetIt getIt = GetIt.instance;

/// Registers app-wide dependencies. Call once from `main()` before `runApp`.
/// Generated by `injectable`/`build_runner` from the `@LazySingleton`/
/// `@injectable` annotations on the registered classes - see
/// `injection.config.dart`. Re-run
/// `flutter pub run build_runner build --delete-conflicting-outputs`
/// after adding or changing an annotated class.
@InjectableInit()
void configureDependencies() => getIt.init();
